name: endo
channels: [conda-forge, bioconda]
dependencies:
  - python=3.11
  - scanpy
  - anndata
  - python-igraph
  - leidenalg
  - harmonypy
  - scikit-misc
  - scikit-learn
  - pandas
  - numpy
  - scipy
  - matplotlib
  - pip
  - pip:
    - infercnvpy
